spring:
  application:
    name: "comic-service"
  datasource:
    url: jdbc:postgresql://localhost:5432/comic_backend_comic_service_db
    username: postgres
    password: 1409
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8763
