spring:
  application:
    name: "media-service"
  data:
    mongodb:
      uri: mongodb://admin:1409@localhost:27017/media_backend_media_service_db?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: top.telecomic.mediaservice.dto.request.MediaFileUpdateRequest
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8765
management:
  endpoints:
    web:
      exposure:
        include: "*"
media:
  access:
    prefix: "/files"
  storage:
    directory: "uploads"
  avatar:
    directory: "avatars"
    max-size: 5MB
  chapter:
    directory: "chapters"
    max-size: 10MB
  thumbnail:
    directory: "thumbnails"
    max-size: 2MB
